name: Hexo Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

      - uses: yrpang/github-actions-hexo@v1.3
        with:
          deploykey: ${{secrets.HEXO_DEPLOY_PRI}}
          username: david4958606
          email: david.wang@kirinou.top